### ISSUE TITLE
Баг OpenCV при сборке проекта

### ISSUE THREAD

**Issue by DVukalov** [cvlabmiet/cvclasses18#2]
При выполнении команды cmake --build . --config Release возникают ошибки
![image](https://user-images.githubusercontent.com/18100235/45267289-53342d80-b472-11e8-945d-98a0017ce389.png)

 error C2039: 'random_shuffle': is not a member of 'std'
error C3861: 'random_shuffle': identifier not found

Если закоментировать строки в файлах random.h, lsh_table.h, связанные с этими ошибками, то проект собирается с предупреждением
![image](https://user-images.githubusercontent.com/18100235/45267318-ca69c180-b472-11e8-831c-f919b28b12e6.png)

Это нормально?

**Comment by rgolovanov** [comment]
Проект сконфигурирован для сборки с версией `c++17`. В этой версии стандарта `c++` были изменены некоторые функции стандартной библиотеки (STL), в том числе  `std::random_shuffle` была заменена на `std::shuffle`.

То есть в нашем проекте требования по версии языка завышены, так как OpenCV, видимо, поддерживает C++14.

В качестве решения предлагаю в нашем репозитории в файлах `CMakeLists.txt` заменить строку
```
set(CMAKE_CXX_STANDARD 17)
```
на
```
set(CMAKE_CXX_STANDARD 14)
```
@dvukalov если сработает, можно отдельным pull request-ом внести исправление

**Comment by DVukalov** [comment]
сработало, осталось только предупреждение,
![image](https://user-images.githubusercontent.com/18100235/45267816-6946eb80-b47c-11e8-9970-783e29b5d817.png)
